services:
  - name: pingone-hello
    type: web
    runtime: node
    plan: starter
    buildCommand: "npm install --omit=dev"
    startCommand: "node server.js"
    envVars:
      - key: OIDC_BASEURL
        sync: false # already set in Render dashboard
      - key: OIDC_CLIENT_ID
        sync: false # set manually in dashboard
      - key: SESSION_SECRET
        sync: false # set manually in dashboard
